/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#8e9192',
        'secondary-fixed-dim': '#c7c6c4',
        'tertiary-fixed': '#f7e382',
        'inverse-primary': '#5f5e5e',
        'on-error': '#690005',
        'surface-bright': '#393939',
        'inverse-surface': '#e4e2e1',
        'on-primary-container': '#7b7979',
        'tertiary-container': '#0d0a00',
        'surface-dim': '#131313',
        'on-primary-fixed': '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'primary-container': '#0a0a0a',
        'surface-container-low': '#1b1c1c',
        'on-secondary-container': '#b5b5b2',
        error: '#ffb4ab',
        'secondary-fixed': '#e3e2e0',
        secondary: '#c7c6c4',
        'on-tertiary-fixed': '#211b00',
        'on-secondary': '#2f312f',
        'on-tertiary-container': '#897924',
        primary: '#c9c6c5',
        tertiary: '#dac769',
        'on-secondary-fixed-variant': '#464745',
        'primary-fixed': '#e5e2e1',
        'on-secondary-fixed': '#1a1c1a',
        'on-tertiary': '#393000',
        'on-tertiary-fixed-variant': '#524700',
        'on-surface': '#e4e2e1',
        'inverse-on-surface': '#303030',
        'on-primary': '#313030',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-highest': '#353535',
        'on-background': '#e4e2e1',
        'surface-container': '#1f2020',
        'surface-variant': '#353535',
        'on-primary-fixed-variant': '#474646',
        'on-surface-variant': '#c4c7c7',
        'surface-tint': '#c9c6c5',
        'primary-fixed-dim': '#c9c6c5',
        surface: '#131313',
        'on-error-container': '#ffdad6',
        'outline-variant': '#444748',
        'error-container': '#93000a',
        'secondary-container': '#464745',
        'tertiary-fixed-dim': '#dac769',
        background: '#131313',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '80px',
        'margin-mobile': '24px',
        unit: '8px',
        'section-gap': '160px',
        gutter: '32px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'body-md': ['Montserrat', 'sans-serif'],
        'display-lg-mobile': ['"Bodoni Moda"', 'serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'headline-lg': ['"Bodoni Moda"', 'serif'],
        'display-lg': ['"Bodoni Moda"', 'serif'],
        'label-caps': ['Montserrat', 'sans-serif'],
        'headline-md': ['"Bodoni Moda"', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg-mobile': [
          '48px',
          { lineHeight: '54px', letterSpacing: '-0.01em', fontWeight: '400' },
        ],
        'body-lg': [
          '18px',
          { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '300' },
        ],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '400' }],
        'display-lg': [
          '80px',
          { lineHeight: '90px', letterSpacing: '-0.02em', fontWeight: '400' },
        ],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.15em', fontWeight: '600' },
        ],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
